[ADD] sale_order_line_date_next_reception
akretion/odoo-usability pull request #218
Opened 2024-06-24 15:53 UTC by mathieudelva

2024-07-04 07:38 UTC, sebastienbeau commented on sale_order_line_date_next_reception/models/sale_order_line.py
> +            if not(line.product_id.qty_available) and line.state not in ['done', 'cancel']:
You should test "line.product_id.qty_available < 0" as the qty available can be negatif

2024-07-04 08:05 UTC, bealdav commented
Hi @sebastienbeau @mathieudelva 

Thanks for this contribution. I'm also work on this kind of topic ;-)

But it seems not related to odoo-usability ?

Why don't you share in OCA directly ?

Thanks for your feedback

2024-07-04 09:07 UTC, sebastienbeau requested changes

2024-07-04 09:07 UTC, sebastienbeau commented on sale_order_line_date_next_reception/models/sale_order_line.py
> +                line.date_next_reception = picking_id and picking_id[0].scheduled_date.date()
```suggestion
                    ], limit=1)
                line.date_next_reception = picking_id.scheduled_date
```

2024-07-05 07:33 UTC, mathieudelva commented
Hi @sebastienbeau @bealdav 

I moved the module to sale-workflow:
https://github.com/OCA/sale-workflow/pull/3223

2024-07-05 07:33 UTC, closed without merging